// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainzInfo.Data;

#nullable disable

namespace TrainzInfo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241208073958_TablesUpdates")]
    partial class TablesUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoleUsers", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUsers");
                });

            modelBuilder.Entity("TrainzInfo.Models.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("IsStationExist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oblast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Oblastsid")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Oblastsid");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TrainzInfo.Models.DepotList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Cityid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UkrainsRailwayid")
                        .HasColumnType("int");

                    b.Property<string>("UkrainsRailways")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Cityid");

                    b.HasIndex("UkrainsRailwayid");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("TrainzInfo.Models.DieselTrains", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepotListid")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberTrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuburbanTrainsInfoid")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotListid");

                    b.HasIndex("SuburbanTrainsInfoid");

                    b.HasIndex("UsersId");

                    b.ToTable("DieselTrains");
                });

            modelBuilder.Entity("TrainzInfo.Models.ElectricTrain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Cityid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepotCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepotListid")
                        .HasColumnType("int");

                    b.Property<string>("DepotTrain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElectrickTrainzInformationid")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastKvr")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceKvr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Plantsid")
                        .HasColumnType("int");

                    b.Property<int?>("Trainsid")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.Property<string>("VagonsCountP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Cityid");

                    b.HasIndex("DepotListid");

                    b.HasIndex("ElectrickTrainzInformationid");

                    b.HasIndex("Plantsid");

                    b.HasIndex("Trainsid");

                    b.HasIndex("UsersId");

                    b.ToTable("Electrics");
                });

            modelBuilder.Entity("TrainzInfo.Models.ElectrickTrainzInformation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AllInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ElectrickTrainzInformation");
                });

            modelBuilder.Entity("TrainzInfo.Models.IpAdresses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UsersId");

                    b.ToTable("IpAdresses");
                });

            modelBuilder.Entity("TrainzInfo.Models.Locomotive", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Depot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepotListid")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocomotiveBaseInfoid")
                        .HasColumnType("int");

                    b.Property<int?>("Locomotive_Seriesid")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("DepotListid");

                    b.HasIndex("LocomotiveBaseInfoid");

                    b.HasIndex("Locomotive_Seriesid");

                    b.ToTable("Locomotives");
                });

            modelBuilder.Entity("TrainzInfo.Models.LocomotiveBaseInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("LocomotiveBaseInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Locomotive_series", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Seria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Locomotive_Series");
                });

            modelBuilder.Entity("TrainzInfo.Models.MainImages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UsersId");

                    b.ToTable("MainImages");
                });

            modelBuilder.Entity("TrainzInfo.Models.Metro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Metros");
                });

            modelBuilder.Entity("TrainzInfo.Models.MetroLines", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CountStation")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Metroid")
                        .HasColumnType("int");

                    b.Property<string>("NameLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Metroid");

                    b.ToTable("MetroLines");
                });

            modelBuilder.Entity("TrainzInfo.Models.MetroStation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetroID")
                        .HasColumnType("int");

                    b.Property<string>("MetroLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetroLineId")
                        .HasColumnType("int");

                    b.Property<int?>("MetroLinesid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("MetroLinesid");

                    b.ToTable("MetroStations");
                });

            modelBuilder.Entity("TrainzInfo.Models.NewsComments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NewsInfoid")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsInfoid");

                    b.HasIndex("UsersId");

                    b.ToTable("NewsComments");
                });

            modelBuilder.Entity("TrainzInfo.Models.NewsInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BaseNewsInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateTime")
                        .HasColumnType("date");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgsrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameNews")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("NewsImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NewsInfoAll")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UsersId");

                    b.ToTable("NewsInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Oblast", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OblCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Oblasts");
                });

            modelBuilder.Entity("TrainzInfo.Models.Plants", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("TrainzInfo.Models.RailwayUsersPhoto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Stationsid");

                    b.HasIndex("UsersId");

                    b.ToTable("RailwayUsersPhotos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TrainzInfo.Models.StationInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StationInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Stations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Citysid")
                        .HasColumnType("int");

                    b.Property<string>("DopImgSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DopImgSrcSec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DopImgSrcThd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgsrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Metroid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oblast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Oblastsid")
                        .HasColumnType("int");

                    b.Property<string>("Railway")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StationInfoid")
                        .HasColumnType("int");

                    b.Property<int?>("UkrainsRailwaysid")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Citysid");

                    b.HasIndex("Metroid");

                    b.HasIndex("Oblastsid");

                    b.HasIndex("StationInfoid");

                    b.HasIndex("UkrainsRailwaysid");

                    b.HasIndex("UsersId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainzInfo.Models.StationsShadule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("NumberTrain")
                        .HasColumnType("int");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeOfArrive")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeOfDepet")
                        .HasColumnType("time");

                    b.Property<int?>("Trainid")
                        .HasColumnType("int");

                    b.Property<int?>("UkrainsRailwaysid")
                        .HasColumnType("int");

                    b.Property<string>("UzFilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Stationsid");

                    b.HasIndex("Trainid");

                    b.HasIndex("UkrainsRailwaysid");

                    b.ToTable("StationsShadules");
                });

            modelBuilder.Entity("TrainzInfo.Models.SuburbanTrainsInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SuburbanTrainsInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Train", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Fromid")
                        .HasColumnType("int");

                    b.Property<string>("NameOfTrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("StationFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Toid")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeOfPassTrainid")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Fromid");

                    b.HasIndex("Toid");

                    b.HasIndex("TypeOfPassTrainid");

                    b.HasIndex("UserId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("TrainzInfo.Models.TrainsShadule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<TimeSpan>("Arrival")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Departure")
                        .HasColumnType("time");

                    b.Property<string>("Distance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberTrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<int?>("Trainid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Stationsid");

                    b.HasIndex("Trainid");

                    b.ToTable("TrainsShadule");
                });

            modelBuilder.Entity("TrainzInfo.Models.TypeOfPassTrain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TypeOfPassTrains");
                });

            modelBuilder.Entity("TrainzInfo.Models.UkrainsRailways", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UsersId");

                    b.ToTable("UkrainsRailways");
                });

            modelBuilder.Entity("TrainzInfo.Models.UserLocomotivePhotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Locomotiveid")
                        .HasColumnType("int");

                    b.Property<string>("NameLocomotive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Locomotiveid");

                    b.HasIndex("UserId");

                    b.ToTable("UserLocomotivePhotos");
                });

            modelBuilder.Entity("TrainzInfo.Models.UserTrainzPhoto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UseridId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Stationsid");

                    b.HasIndex("UseridId");

                    b.ToTable("UserTrainzPhotos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RoleUsers", b =>
                {
                    b.HasOne("TrainzInfo.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainzInfo.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainzInfo.Models.City", b =>
                {
                    b.HasOne("TrainzInfo.Models.Oblast", "Oblasts")
                        .WithMany("Cities")
                        .HasForeignKey("Oblastsid");

                    b.Navigation("Oblasts");
                });

            modelBuilder.Entity("TrainzInfo.Models.DepotList", b =>
                {
                    b.HasOne("TrainzInfo.Models.City", "City")
                        .WithMany("DepotLists")
                        .HasForeignKey("Cityid");

                    b.HasOne("TrainzInfo.Models.UkrainsRailways", "UkrainsRailway")
                        .WithMany("DepotLists")
                        .HasForeignKey("UkrainsRailwayid");

                    b.Navigation("City");

                    b.Navigation("UkrainsRailway");
                });

            modelBuilder.Entity("TrainzInfo.Models.DieselTrains", b =>
                {
                    b.HasOne("TrainzInfo.Models.DepotList", "DepotList")
                        .WithMany("DieselTrains")
                        .HasForeignKey("DepotListid");

                    b.HasOne("TrainzInfo.Models.SuburbanTrainsInfo", "SuburbanTrainsInfo")
                        .WithMany("DieselTrains")
                        .HasForeignKey("SuburbanTrainsInfoid");

                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("DepotList");

                    b.Navigation("SuburbanTrainsInfo");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.ElectricTrain", b =>
                {
                    b.HasOne("TrainzInfo.Models.City", "City")
                        .WithMany("ElectricTrains")
                        .HasForeignKey("Cityid");

                    b.HasOne("TrainzInfo.Models.DepotList", "DepotList")
                        .WithMany("ElectricTrains")
                        .HasForeignKey("DepotListid");

                    b.HasOne("TrainzInfo.Models.ElectrickTrainzInformation", "ElectrickTrainzInformation")
                        .WithMany()
                        .HasForeignKey("ElectrickTrainzInformationid");

                    b.HasOne("TrainzInfo.Models.Plants", "Plants")
                        .WithMany("electricTrains")
                        .HasForeignKey("Plantsid");

                    b.HasOne("TrainzInfo.Models.SuburbanTrainsInfo", "Trains")
                        .WithMany("ElectricTrain")
                        .HasForeignKey("Trainsid");

                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("City");

                    b.Navigation("DepotList");

                    b.Navigation("ElectrickTrainzInformation");

                    b.Navigation("Plants");

                    b.Navigation("Trains");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.IpAdresses", b =>
                {
                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany("IpAdresses")
                        .HasForeignKey("UsersId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.Locomotive", b =>
                {
                    b.HasOne("TrainzInfo.Models.DepotList", "DepotList")
                        .WithMany("Locomotives")
                        .HasForeignKey("DepotListid");

                    b.HasOne("TrainzInfo.Models.LocomotiveBaseInfo", "LocomotiveBaseInfo")
                        .WithMany()
                        .HasForeignKey("LocomotiveBaseInfoid");

                    b.HasOne("TrainzInfo.Models.Locomotive_series", "Locomotive_Series")
                        .WithMany("Locomotives")
                        .HasForeignKey("Locomotive_Seriesid");

                    b.Navigation("DepotList");

                    b.Navigation("LocomotiveBaseInfo");

                    b.Navigation("Locomotive_Series");
                });

            modelBuilder.Entity("TrainzInfo.Models.MainImages", b =>
                {
                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.MetroLines", b =>
                {
                    b.HasOne("TrainzInfo.Models.Metro", "Metro")
                        .WithMany("MetroLines")
                        .HasForeignKey("Metroid");

                    b.Navigation("Metro");
                });

            modelBuilder.Entity("TrainzInfo.Models.MetroStation", b =>
                {
                    b.HasOne("TrainzInfo.Models.MetroLines", "MetroLines")
                        .WithMany("Stations")
                        .HasForeignKey("MetroLinesid");

                    b.Navigation("MetroLines");
                });

            modelBuilder.Entity("TrainzInfo.Models.NewsComments", b =>
                {
                    b.HasOne("TrainzInfo.Models.NewsInfo", "NewsInfo")
                        .WithMany("NewsComments")
                        .HasForeignKey("NewsInfoid");

                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("NewsInfo");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.NewsInfo", b =>
                {
                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.RailwayUsersPhoto", b =>
                {
                    b.HasOne("TrainzInfo.Models.Stations", "Stations")
                        .WithMany("railwayUsersPhotos")
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany("RailwayUsersPhotos")
                        .HasForeignKey("UsersId");

                    b.Navigation("Stations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.Stations", b =>
                {
                    b.HasOne("TrainzInfo.Models.City", "Citys")
                        .WithMany("Stations")
                        .HasForeignKey("Citysid");

                    b.HasOne("TrainzInfo.Models.Metro", "Metro")
                        .WithMany()
                        .HasForeignKey("Metroid");

                    b.HasOne("TrainzInfo.Models.Oblast", "Oblasts")
                        .WithMany("Stations")
                        .HasForeignKey("Oblastsid");

                    b.HasOne("TrainzInfo.Models.StationInfo", "StationInfo")
                        .WithMany()
                        .HasForeignKey("StationInfoid");

                    b.HasOne("TrainzInfo.Models.UkrainsRailways", "UkrainsRailways")
                        .WithMany("Stations")
                        .HasForeignKey("UkrainsRailwaysid");

                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany("Stations")
                        .HasForeignKey("UsersId");

                    b.Navigation("Citys");

                    b.Navigation("Metro");

                    b.Navigation("Oblasts");

                    b.Navigation("StationInfo");

                    b.Navigation("UkrainsRailways");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.StationsShadule", b =>
                {
                    b.HasOne("TrainzInfo.Models.Stations", "Stations")
                        .WithMany("StationsShadules")
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfo.Models.Train", "Train")
                        .WithMany("StationsShadules")
                        .HasForeignKey("Trainid");

                    b.HasOne("TrainzInfo.Models.UkrainsRailways", "UkrainsRailways")
                        .WithMany("stationsShadules")
                        .HasForeignKey("UkrainsRailwaysid");

                    b.Navigation("Stations");

                    b.Navigation("Train");

                    b.Navigation("UkrainsRailways");
                });

            modelBuilder.Entity("TrainzInfo.Models.Train", b =>
                {
                    b.HasOne("TrainzInfo.Models.Stations", "From")
                        .WithMany()
                        .HasForeignKey("Fromid");

                    b.HasOne("TrainzInfo.Models.Stations", "To")
                        .WithMany()
                        .HasForeignKey("Toid");

                    b.HasOne("TrainzInfo.Models.TypeOfPassTrain", "TypeOfPassTrain")
                        .WithMany("Trains")
                        .HasForeignKey("TypeOfPassTrainid");

                    b.HasOne("TrainzInfo.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("From");

                    b.Navigation("To");

                    b.Navigation("TypeOfPassTrain");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainzInfo.Models.TrainsShadule", b =>
                {
                    b.HasOne("TrainzInfo.Models.Stations", "Stations")
                        .WithMany()
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfo.Models.Train", "Train")
                        .WithMany("TrainsShadules")
                        .HasForeignKey("Trainid");

                    b.Navigation("Stations");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainzInfo.Models.UkrainsRailways", b =>
                {
                    b.HasOne("TrainzInfo.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainzInfo.Models.UserLocomotivePhotos", b =>
                {
                    b.HasOne("TrainzInfo.Models.Locomotive", "Locomotive")
                        .WithMany("UserLocomotivesPhoto")
                        .HasForeignKey("Locomotiveid");

                    b.HasOne("TrainzInfo.Models.Users", "User")
                        .WithMany("UserLocomotivePhotos")
                        .HasForeignKey("UserId");

                    b.Navigation("Locomotive");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainzInfo.Models.UserTrainzPhoto", b =>
                {
                    b.HasOne("TrainzInfo.Models.Stations", "Stations")
                        .WithMany()
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfo.Models.Users", "Userid")
                        .WithMany("UserTrainzPhotos")
                        .HasForeignKey("UseridId");

                    b.Navigation("Stations");

                    b.Navigation("Userid");
                });

            modelBuilder.Entity("TrainzInfo.Models.City", b =>
                {
                    b.Navigation("DepotLists");

                    b.Navigation("ElectricTrains");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfo.Models.DepotList", b =>
                {
                    b.Navigation("DieselTrains");

                    b.Navigation("ElectricTrains");

                    b.Navigation("Locomotives");
                });

            modelBuilder.Entity("TrainzInfo.Models.Locomotive", b =>
                {
                    b.Navigation("UserLocomotivesPhoto");
                });

            modelBuilder.Entity("TrainzInfo.Models.Locomotive_series", b =>
                {
                    b.Navigation("Locomotives");
                });

            modelBuilder.Entity("TrainzInfo.Models.Metro", b =>
                {
                    b.Navigation("MetroLines");
                });

            modelBuilder.Entity("TrainzInfo.Models.MetroLines", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfo.Models.NewsInfo", b =>
                {
                    b.Navigation("NewsComments");
                });

            modelBuilder.Entity("TrainzInfo.Models.Oblast", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfo.Models.Plants", b =>
                {
                    b.Navigation("electricTrains");
                });

            modelBuilder.Entity("TrainzInfo.Models.Stations", b =>
                {
                    b.Navigation("StationsShadules");

                    b.Navigation("railwayUsersPhotos");
                });

            modelBuilder.Entity("TrainzInfo.Models.SuburbanTrainsInfo", b =>
                {
                    b.Navigation("DieselTrains");

                    b.Navigation("ElectricTrain");
                });

            modelBuilder.Entity("TrainzInfo.Models.Train", b =>
                {
                    b.Navigation("StationsShadules");

                    b.Navigation("TrainsShadules");
                });

            modelBuilder.Entity("TrainzInfo.Models.TypeOfPassTrain", b =>
                {
                    b.Navigation("Trains");
                });

            modelBuilder.Entity("TrainzInfo.Models.UkrainsRailways", b =>
                {
                    b.Navigation("DepotLists");

                    b.Navigation("Stations");

                    b.Navigation("stationsShadules");
                });

            modelBuilder.Entity("TrainzInfo.Models.Users", b =>
                {
                    b.Navigation("IpAdresses");

                    b.Navigation("RailwayUsersPhotos");

                    b.Navigation("Stations");

                    b.Navigation("UserLocomotivePhotos");

                    b.Navigation("UserTrainzPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
