// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainzInfo.Data;

#nullable disable

namespace TrainzInfo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260226175256_News_Status")]
    partial class News_Status
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.Addresses.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("IsStationExist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oblast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Oblastsid")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Oblastsid");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.Addresses.Oblast", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OblCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Oblasts");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.IpAdresses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IpAddres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("IpAdresses");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.MailSettings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("bit");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MailSettings");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.MainImages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MainImages");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.Plants", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.SendEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId");

                    b.ToTable("SendEmails");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.StatusObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusObjects");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.TypeOfPassTrain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TypeOfPassTrains");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.DepotList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Cityid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UkrainsRailwayid")
                        .HasColumnType("int");

                    b.Property<string>("UkrainsRailways")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Cityid");

                    b.HasIndex("UkrainsRailwayid");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.ElectrickTrainzInformation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AllInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ElectrickTrainzInformation");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.LocomotiveBaseInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("LocomotiveBaseInfos");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.Locomotive_series", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Locomotive_Series");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.StationInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StationInfos");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.SuburbanTrainsInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SuburbanTrainsInfos");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Images.NewsImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewsInfoId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("NewsInfoId")
                        .IsUnique();

                    b.ToTable("NewsImages");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Images.StationImages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StationImages");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.DieselTrains", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepotListid")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberTrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<int?>("SuburbanTrainsInfoid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepotListid");

                    b.HasIndex("Stationsid");

                    b.HasIndex("SuburbanTrainsInfoid");

                    b.ToTable("DieselTrains");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.ElectricTrain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Cityid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("CreatedTrain")
                        .HasColumnType("date");

                    b.Property<string>("DepotCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepotListid")
                        .HasColumnType("int");

                    b.Property<string>("DepotTrain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElectrickTrainzInformationid")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("LastKvr")
                        .HasColumnType("date");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantCreate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantKvr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantsCreateid")
                        .HasColumnType("int");

                    b.Property<int?>("PlantsKvrid")
                        .HasColumnType("int");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<int?>("Trainsid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Cityid");

                    b.HasIndex("DepotListid");

                    b.HasIndex("ElectrickTrainzInformationid");

                    b.HasIndex("PlantsCreateid");

                    b.HasIndex("PlantsKvrid");

                    b.HasIndex("Stationsid");

                    b.HasIndex("Trainsid");

                    b.ToTable("Electrics");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.Locomotive", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime2");

                    b.Property<string>("Depot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepotListid")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocomotiveBaseInfoid")
                        .HasColumnType("int");

                    b.Property<int?>("Locomotive_Seriesid")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("DepotListid");

                    b.HasIndex("LocomotiveBaseInfoid");

                    b.HasIndex("Locomotive_Seriesid");

                    b.HasIndex("Stationsid");

                    b.ToTable("Locomotives");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.Metro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Metros");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.MetroLines", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CountStation")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Metroid")
                        .HasColumnType("int");

                    b.Property<string>("NameLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Metroid");

                    b.ToTable("MetroLines");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.MetroStation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetroID")
                        .HasColumnType("int");

                    b.Property<string>("MetroLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetroLineId")
                        .HasColumnType("int");

                    b.Property<int?>("MetroLinesid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("MetroLinesid");

                    b.ToTable("MetroStations");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.NewsComments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NewsInfoid")
                        .HasColumnType("int");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("NewsInfoid");

                    b.ToTable("NewsComments");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.NewsInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BaseNewsInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEndActual")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateStartActual")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkSorce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameNews")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsInfoAll")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("NewsInfos");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.Stations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Citysid")
                        .HasColumnType("int");

                    b.Property<string>("DopImgSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DopImgSrcSec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DopImgSrcThd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgsrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Metroid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oblast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Oblastsid")
                        .HasColumnType("int");

                    b.Property<string>("Railway")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StationImagesid")
                        .HasColumnType("int");

                    b.Property<int?>("StationInfoid")
                        .HasColumnType("int");

                    b.Property<int?>("UkrainsRailwaysid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Citysid");

                    b.HasIndex("Metroid");

                    b.HasIndex("Oblastsid");

                    b.HasIndex("StationImagesid");

                    b.HasIndex("StationInfoid");

                    b.HasIndex("UkrainsRailwaysid");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.UkrainsRailways", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UkrainsRailways");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.PlanningRoute.PlanningUserRoute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanningUserRouteSaveID")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("TrainsShaduleID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PlanningUserRouteSaveID");

                    b.HasIndex("UserId");

                    b.ToTable("PlanningUserRoutes");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.PlanningRoute.PlanningUserRouteSave", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Arrive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depeat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("PlanningUserRouteSaves");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.PlanningRoute.PlanningUserTrains", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanningUserRouteSaveID")
                        .HasColumnType("int");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PlanningUserRouteSaveID");

                    b.HasIndex("TrainID");

                    b.HasIndex("UserId");

                    b.ToTable("PlanningUserTrains");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.System.DocumentToIndex", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Citiesid")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Depotsid")
                        .HasColumnType("int");

                    b.Property<int?>("DieselTrainsId")
                        .HasColumnType("int");

                    b.Property<int?>("Electricid")
                        .HasColumnType("int");

                    b.Property<int?>("ElectrickTrainzInformationid")
                        .HasColumnType("int");

                    b.Property<int?>("IpAdressesid")
                        .HasColumnType("int");

                    b.Property<int?>("LocomotiveBaseInfosid")
                        .HasColumnType("int");

                    b.Property<int?>("Locomotive_Seriesid")
                        .HasColumnType("int");

                    b.Property<int?>("Locomotiveid")
                        .HasColumnType("int");

                    b.Property<int?>("MailSettingsid")
                        .HasColumnType("int");

                    b.Property<int?>("MainImagesid")
                        .HasColumnType("int");

                    b.Property<int?>("MetroLinesid")
                        .HasColumnType("int");

                    b.Property<int?>("MetroStationsid")
                        .HasColumnType("int");

                    b.Property<int?>("Metrosid")
                        .HasColumnType("int");

                    b.Property<string>("NameObject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewsCommentsId")
                        .HasColumnType("int");

                    b.Property<int?>("NewsImageid")
                        .HasColumnType("int");

                    b.Property<int?>("NewsInfoid")
                        .HasColumnType("int");

                    b.Property<int?>("Oblastsid")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanningUserRouteID")
                        .HasColumnType("int");

                    b.Property<int?>("PlanningUserRouteSavesID")
                        .HasColumnType("int");

                    b.Property<int?>("PlanningUserTrainID")
                        .HasColumnType("int");

                    b.Property<int?>("Plantsid")
                        .HasColumnType("int");

                    b.Property<int?>("RailwayUsersPhotosid")
                        .HasColumnType("int");

                    b.Property<string>("SearchContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SendEmailsId")
                        .HasColumnType("int");

                    b.Property<int?>("StationImageid")
                        .HasColumnType("int");

                    b.Property<int?>("StationInfosid")
                        .HasColumnType("int");

                    b.Property<int?>("StationsShaduleid")
                        .HasColumnType("int");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<int?>("SuburbanTrainsInfosid")
                        .HasColumnType("int");

                    b.Property<int?>("TrainsShaduleid")
                        .HasColumnType("int");

                    b.Property<int?>("Trainsid")
                        .HasColumnType("int");

                    b.Property<int?>("TypeOfPassTrainsid")
                        .HasColumnType("int");

                    b.Property<int?>("UkrainsRailwaysid")
                        .HasColumnType("int");

                    b.Property<int?>("UserLocomotivePhotoId")
                        .HasColumnType("int");

                    b.Property<int?>("UserTrainzPhotoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Citiesid");

                    b.HasIndex("Depotsid");

                    b.HasIndex("DieselTrainsId");

                    b.HasIndex("Electricid");

                    b.HasIndex("ElectrickTrainzInformationid");

                    b.HasIndex("IpAdressesid");

                    b.HasIndex("LocomotiveBaseInfosid");

                    b.HasIndex("Locomotive_Seriesid");

                    b.HasIndex("Locomotiveid");

                    b.HasIndex("MailSettingsid");

                    b.HasIndex("MainImagesid");

                    b.HasIndex("MetroLinesid");

                    b.HasIndex("MetroStationsid");

                    b.HasIndex("Metrosid");

                    b.HasIndex("NewsCommentsId");

                    b.HasIndex("NewsImageid");

                    b.HasIndex("NewsInfoid");

                    b.HasIndex("Oblastsid");

                    b.HasIndex("PlanningUserRouteID");

                    b.HasIndex("PlanningUserRouteSavesID");

                    b.HasIndex("PlanningUserTrainID");

                    b.HasIndex("Plantsid");

                    b.HasIndex("RailwayUsersPhotosid");

                    b.HasIndex("SendEmailsId");

                    b.HasIndex("StationImageid");

                    b.HasIndex("StationInfosid");

                    b.HasIndex("StationsShaduleid");

                    b.HasIndex("Stationsid");

                    b.HasIndex("SuburbanTrainsInfosid");

                    b.HasIndex("TrainsShaduleid");

                    b.HasIndex("Trainsid");

                    b.HasIndex("TypeOfPassTrainsid");

                    b.HasIndex("UkrainsRailwaysid");

                    b.HasIndex("UserLocomotivePhotoId");

                    b.HasIndex("UserTrainzPhotoid");

                    b.ToTable("DocumentToIndex");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Trains.StationsShadule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsUsing")
                        .HasColumnType("bit");

                    b.Property<int>("NumberTrain")
                        .HasColumnType("int");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeOfArrive")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeOfDepet")
                        .HasColumnType("time");

                    b.Property<int?>("Trainid")
                        .HasColumnType("int");

                    b.Property<int?>("UkrainsRailwaysid")
                        .HasColumnType("int");

                    b.Property<string>("UzFilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Stationsid");

                    b.HasIndex("Trainid");

                    b.HasIndex("UkrainsRailwaysid");

                    b.ToTable("StationsShadules");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Trains.Train", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Fromid")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsing")
                        .HasColumnType("bit");

                    b.Property<string>("NameOfTrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Toid")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeOfPassTrainid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Fromid");

                    b.HasIndex("Toid");

                    b.HasIndex("TypeOfPassTrainid");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Trains.TrainsShadule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<TimeSpan>("Arrival")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Departure")
                        .HasColumnType("time");

                    b.Property<string>("Distance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUsing")
                        .HasColumnType("bit");

                    b.Property<string>("NameStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberTrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanningUserRouteID")
                        .HasColumnType("int");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<int?>("Trainid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PlanningUserRouteID");

                    b.HasIndex("Stationsid");

                    b.HasIndex("Trainid");

                    b.ToTable("TrainsShadule");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.UsersInfo.RailwayUsersPhoto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Stationsid");

                    b.ToTable("RailwayUsersPhotos");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.UsersInfo.UserLocomotivePhotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Locomotiveid")
                        .HasColumnType("int");

                    b.Property<string>("NameLocomotive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Locomotiveid");

                    b.ToTable("UserLocomotivePhotos");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.UsersInfo.UserTrainzPhoto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stationsid")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Stationsid");

                    b.ToTable("UserTrainzPhotos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.Addresses.City", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Dictionaries.Addresses.Oblast", "Oblasts")
                        .WithMany("Cities")
                        .HasForeignKey("Oblastsid");

                    b.Navigation("Oblasts");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.IpAdresses", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.SendEmail", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.DepotList", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Dictionaries.Addresses.City", "City")
                        .WithMany("DepotLists")
                        .HasForeignKey("Cityid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.UkrainsRailways", "UkrainsRailway")
                        .WithMany("DepotLists")
                        .HasForeignKey("UkrainsRailwayid");

                    b.Navigation("City");

                    b.Navigation("UkrainsRailway");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Images.NewsImage", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Main.NewsInfo", null)
                        .WithOne("NewsImages")
                        .HasForeignKey("TrainzInfoModel.Models.Information.Images.NewsImage", "NewsInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.DieselTrains", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Additional.DepotList", "DepotList")
                        .WithMany("DieselTrains")
                        .HasForeignKey("DepotListid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "Stations")
                        .WithMany("DieselTrains")
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.SuburbanTrainsInfo", "SuburbanTrainsInfo")
                        .WithMany("DieselTrains")
                        .HasForeignKey("SuburbanTrainsInfoid");

                    b.Navigation("DepotList");

                    b.Navigation("Stations");

                    b.Navigation("SuburbanTrainsInfo");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.ElectricTrain", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Dictionaries.Addresses.City", "City")
                        .WithMany("ElectricTrains")
                        .HasForeignKey("Cityid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.DepotList", "DepotList")
                        .WithMany("ElectricTrains")
                        .HasForeignKey("DepotListid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.ElectrickTrainzInformation", "ElectrickTrainzInformation")
                        .WithMany()
                        .HasForeignKey("ElectrickTrainzInformationid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.Plants", "PlantsCreate")
                        .WithMany()
                        .HasForeignKey("PlantsCreateid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.Plants", "PlantsKvr")
                        .WithMany()
                        .HasForeignKey("PlantsKvrid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "Stations")
                        .WithMany("ElectricTrains")
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.SuburbanTrainsInfo", "Trains")
                        .WithMany("ElectricTrain")
                        .HasForeignKey("Trainsid");

                    b.Navigation("City");

                    b.Navigation("DepotList");

                    b.Navigation("ElectrickTrainzInformation");

                    b.Navigation("PlantsCreate");

                    b.Navigation("PlantsKvr");

                    b.Navigation("Stations");

                    b.Navigation("Trains");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.Locomotive", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Additional.DepotList", "DepotList")
                        .WithMany("Locomotives")
                        .HasForeignKey("DepotListid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.LocomotiveBaseInfo", "LocomotiveBaseInfo")
                        .WithMany()
                        .HasForeignKey("LocomotiveBaseInfoid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.Locomotive_series", "Locomotive_Series")
                        .WithMany("Locomotives")
                        .HasForeignKey("Locomotive_Seriesid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "Stations")
                        .WithMany("Locomotives")
                        .HasForeignKey("Stationsid");

                    b.Navigation("DepotList");

                    b.Navigation("LocomotiveBaseInfo");

                    b.Navigation("Locomotive_Series");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.MetroLines", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Main.Metro", "Metro")
                        .WithMany("MetroLines")
                        .HasForeignKey("Metroid");

                    b.Navigation("Metro");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.MetroStation", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Main.MetroLines", "MetroLines")
                        .WithMany("Stations")
                        .HasForeignKey("MetroLinesid");

                    b.Navigation("MetroLines");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.NewsComments", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.NewsInfo", "NewsInfo")
                        .WithMany("NewsComments")
                        .HasForeignKey("NewsInfoid");

                    b.Navigation("Author");

                    b.Navigation("NewsInfo");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.NewsInfo", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.StatusObject", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.Stations", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Dictionaries.Addresses.City", "Citys")
                        .WithMany("Stations")
                        .HasForeignKey("Citysid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Metro", "Metro")
                        .WithMany()
                        .HasForeignKey("Metroid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.Addresses.Oblast", "Oblasts")
                        .WithMany("Stations")
                        .HasForeignKey("Oblastsid");

                    b.HasOne("TrainzInfoModel.Models.Information.Images.StationImages", "StationImages")
                        .WithMany()
                        .HasForeignKey("StationImagesid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.StationInfo", "StationInfo")
                        .WithMany()
                        .HasForeignKey("StationInfoid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.UkrainsRailways", "UkrainsRailways")
                        .WithMany("Stations")
                        .HasForeignKey("UkrainsRailwaysid");

                    b.Navigation("Citys");

                    b.Navigation("Metro");

                    b.Navigation("Oblasts");

                    b.Navigation("StationImages");

                    b.Navigation("StationInfo");

                    b.Navigation("UkrainsRailways");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.PlanningRoute.PlanningUserRoute", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.PlanningRoute.PlanningUserRouteSave", null)
                        .WithMany("PlanningUserRoute")
                        .HasForeignKey("PlanningUserRouteSaveID");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.PlanningRoute.PlanningUserRouteSave", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.PlanningRoute.PlanningUserTrains", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.PlanningRoute.PlanningUserRouteSave", null)
                        .WithMany("PlanningUserTrains")
                        .HasForeignKey("PlanningUserRouteSaveID");

                    b.HasOne("TrainzInfoModel.Models.Trains.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Train");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.System.DocumentToIndex", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Dictionaries.Addresses.City", "Cities")
                        .WithMany()
                        .HasForeignKey("Citiesid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.DepotList", "Depots")
                        .WithMany()
                        .HasForeignKey("Depotsid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.DieselTrains", "DieselTrains")
                        .WithMany()
                        .HasForeignKey("DieselTrainsId");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.ElectricTrain", "Electric")
                        .WithMany()
                        .HasForeignKey("Electricid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.ElectrickTrainzInformation", "ElectrickTrainzInformation")
                        .WithMany()
                        .HasForeignKey("ElectrickTrainzInformationid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.IpAdresses", "IpAdresses")
                        .WithMany()
                        .HasForeignKey("IpAdressesid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.LocomotiveBaseInfo", "LocomotiveBaseInfos")
                        .WithMany()
                        .HasForeignKey("LocomotiveBaseInfosid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.Locomotive_series", "Locomotive_Series")
                        .WithMany()
                        .HasForeignKey("Locomotive_Seriesid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Locomotive", "Locomotive")
                        .WithMany()
                        .HasForeignKey("Locomotiveid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.MailSettings", "MailSettings")
                        .WithMany()
                        .HasForeignKey("MailSettingsid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.MainImages", "MainImages")
                        .WithMany()
                        .HasForeignKey("MainImagesid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.MetroLines", "MetroLines")
                        .WithMany()
                        .HasForeignKey("MetroLinesid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.MetroStation", "MetroStations")
                        .WithMany()
                        .HasForeignKey("MetroStationsid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Metro", "Metros")
                        .WithMany()
                        .HasForeignKey("Metrosid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.NewsComments", "NewsComments")
                        .WithMany()
                        .HasForeignKey("NewsCommentsId");

                    b.HasOne("TrainzInfoModel.Models.Information.Images.NewsImage", "NewsImage")
                        .WithMany()
                        .HasForeignKey("NewsImageid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.NewsInfo", "NewsInfo")
                        .WithMany()
                        .HasForeignKey("NewsInfoid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.Addresses.Oblast", "Oblasts")
                        .WithMany()
                        .HasForeignKey("Oblastsid");

                    b.HasOne("TrainzInfoModel.Models.PlanningRoute.PlanningUserRoute", "PlanningUserRoute")
                        .WithMany()
                        .HasForeignKey("PlanningUserRouteID");

                    b.HasOne("TrainzInfoModel.Models.PlanningRoute.PlanningUserRouteSave", "PlanningUserRouteSaves")
                        .WithMany()
                        .HasForeignKey("PlanningUserRouteSavesID");

                    b.HasOne("TrainzInfoModel.Models.PlanningRoute.PlanningUserTrains", "PlanningUserTrain")
                        .WithMany()
                        .HasForeignKey("PlanningUserTrainID");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.Plants", "Plants")
                        .WithMany()
                        .HasForeignKey("Plantsid");

                    b.HasOne("TrainzInfoModel.Models.UsersInfo.RailwayUsersPhoto", "RailwayUsersPhotos")
                        .WithMany()
                        .HasForeignKey("RailwayUsersPhotosid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.SendEmail", "SendEmails")
                        .WithMany()
                        .HasForeignKey("SendEmailsId");

                    b.HasOne("TrainzInfoModel.Models.Information.Images.StationImages", "StationImage")
                        .WithMany()
                        .HasForeignKey("StationImageid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.StationInfo", "StationInfos")
                        .WithMany()
                        .HasForeignKey("StationInfosid");

                    b.HasOne("TrainzInfoModel.Models.Trains.StationsShadule", "StationsShadule")
                        .WithMany()
                        .HasForeignKey("StationsShaduleid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "Stations")
                        .WithMany()
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfoModel.Models.Information.Additional.SuburbanTrainsInfo", "SuburbanTrainsInfos")
                        .WithMany()
                        .HasForeignKey("SuburbanTrainsInfosid");

                    b.HasOne("TrainzInfoModel.Models.Trains.TrainsShadule", "TrainsShadule")
                        .WithMany()
                        .HasForeignKey("TrainsShaduleid");

                    b.HasOne("TrainzInfoModel.Models.Trains.Train", "Trains")
                        .WithMany()
                        .HasForeignKey("Trainsid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.TypeOfPassTrain", "TypeOfPassTrains")
                        .WithMany()
                        .HasForeignKey("TypeOfPassTrainsid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.UkrainsRailways", "UkrainsRailways")
                        .WithMany()
                        .HasForeignKey("UkrainsRailwaysid");

                    b.HasOne("TrainzInfoModel.Models.UsersInfo.UserLocomotivePhotos", "UserLocomotivePhoto")
                        .WithMany()
                        .HasForeignKey("UserLocomotivePhotoId");

                    b.HasOne("TrainzInfoModel.Models.UsersInfo.UserTrainzPhoto", "UserTrainzPhoto")
                        .WithMany()
                        .HasForeignKey("UserTrainzPhotoid");

                    b.Navigation("Cities");

                    b.Navigation("Depots");

                    b.Navigation("DieselTrains");

                    b.Navigation("Electric");

                    b.Navigation("ElectrickTrainzInformation");

                    b.Navigation("IpAdresses");

                    b.Navigation("Locomotive");

                    b.Navigation("LocomotiveBaseInfos");

                    b.Navigation("Locomotive_Series");

                    b.Navigation("MailSettings");

                    b.Navigation("MainImages");

                    b.Navigation("MetroLines");

                    b.Navigation("MetroStations");

                    b.Navigation("Metros");

                    b.Navigation("NewsComments");

                    b.Navigation("NewsImage");

                    b.Navigation("NewsInfo");

                    b.Navigation("Oblasts");

                    b.Navigation("PlanningUserRoute");

                    b.Navigation("PlanningUserRouteSaves");

                    b.Navigation("PlanningUserTrain");

                    b.Navigation("Plants");

                    b.Navigation("RailwayUsersPhotos");

                    b.Navigation("SendEmails");

                    b.Navigation("StationImage");

                    b.Navigation("StationInfos");

                    b.Navigation("Stations");

                    b.Navigation("StationsShadule");

                    b.Navigation("SuburbanTrainsInfos");

                    b.Navigation("Trains");

                    b.Navigation("TrainsShadule");

                    b.Navigation("TypeOfPassTrains");

                    b.Navigation("UkrainsRailways");

                    b.Navigation("UserLocomotivePhoto");

                    b.Navigation("UserTrainzPhoto");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Trains.StationsShadule", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "Stations")
                        .WithMany("StationsShadules")
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfoModel.Models.Trains.Train", "Train")
                        .WithMany("StationsShadules")
                        .HasForeignKey("Trainid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.UkrainsRailways", "UkrainsRailways")
                        .WithMany("stationsShadules")
                        .HasForeignKey("UkrainsRailwaysid");

                    b.Navigation("Stations");

                    b.Navigation("Train");

                    b.Navigation("UkrainsRailways");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Trains.Train", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "From")
                        .WithMany()
                        .HasForeignKey("Fromid");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "To")
                        .WithMany()
                        .HasForeignKey("Toid");

                    b.HasOne("TrainzInfoModel.Models.Dictionaries.MetaData.TypeOfPassTrain", "TypeOfPassTrain")
                        .WithMany("Trains")
                        .HasForeignKey("TypeOfPassTrainid");

                    b.Navigation("From");

                    b.Navigation("To");

                    b.Navigation("TypeOfPassTrain");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Trains.TrainsShadule", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.PlanningRoute.PlanningUserRoute", null)
                        .WithMany("TrainsShadule")
                        .HasForeignKey("PlanningUserRouteID");

                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "Stations")
                        .WithMany()
                        .HasForeignKey("Stationsid");

                    b.HasOne("TrainzInfoModel.Models.Trains.Train", "Train")
                        .WithMany("TrainsShadules")
                        .HasForeignKey("Trainid");

                    b.Navigation("Stations");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.UsersInfo.RailwayUsersPhoto", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "Stations")
                        .WithMany("railwayUsersPhotos")
                        .HasForeignKey("Stationsid");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.UsersInfo.UserLocomotivePhotos", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Main.Locomotive", "Locomotive")
                        .WithMany("UserLocomotivesPhoto")
                        .HasForeignKey("Locomotiveid");

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.UsersInfo.UserTrainzPhoto", b =>
                {
                    b.HasOne("TrainzInfoModel.Models.Information.Main.Stations", "Stations")
                        .WithMany()
                        .HasForeignKey("Stationsid");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.Addresses.City", b =>
                {
                    b.Navigation("DepotLists");

                    b.Navigation("ElectricTrains");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.Addresses.Oblast", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Dictionaries.MetaData.TypeOfPassTrain", b =>
                {
                    b.Navigation("Trains");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.DepotList", b =>
                {
                    b.Navigation("DieselTrains");

                    b.Navigation("ElectricTrains");

                    b.Navigation("Locomotives");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.Locomotive_series", b =>
                {
                    b.Navigation("Locomotives");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Additional.SuburbanTrainsInfo", b =>
                {
                    b.Navigation("DieselTrains");

                    b.Navigation("ElectricTrain");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.Locomotive", b =>
                {
                    b.Navigation("UserLocomotivesPhoto");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.Metro", b =>
                {
                    b.Navigation("MetroLines");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.MetroLines", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.NewsInfo", b =>
                {
                    b.Navigation("NewsComments");

                    b.Navigation("NewsImages");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.Stations", b =>
                {
                    b.Navigation("DieselTrains");

                    b.Navigation("ElectricTrains");

                    b.Navigation("Locomotives");

                    b.Navigation("StationsShadules");

                    b.Navigation("railwayUsersPhotos");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Information.Main.UkrainsRailways", b =>
                {
                    b.Navigation("DepotLists");

                    b.Navigation("Stations");

                    b.Navigation("stationsShadules");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.PlanningRoute.PlanningUserRoute", b =>
                {
                    b.Navigation("TrainsShadule");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.PlanningRoute.PlanningUserRouteSave", b =>
                {
                    b.Navigation("PlanningUserRoute");

                    b.Navigation("PlanningUserTrains");
                });

            modelBuilder.Entity("TrainzInfoModel.Models.Trains.Train", b =>
                {
                    b.Navigation("StationsShadules");

                    b.Navigation("TrainsShadules");
                });
#pragma warning restore 612, 618
        }
    }
}
