// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TrainzInfo.Data;

namespace TrainzInfo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("TrainzInfo.Models.CargoCarrieges", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("CargoWeight")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CarriegeType")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.ToTable("CargoCarrieges");
                });

            modelBuilder.Entity("TrainzInfo.Models.CargoCarriegesInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("CargoCarriegesInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TrainzInfo.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TrainzInfo.Models.DepotList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres")
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("UkrainsRailways")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("TrainzInfo.Models.DieselLocomoives", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiseslPower")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("SectionCount")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.ToTable("DieselLocomoives");
                });

            modelBuilder.Entity("TrainzInfo.Models.DieselLocomotiveInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllInfo")
                        .HasColumnType("CLOB");

                    b.Property<string>("Baseinfo")
                        .HasColumnType("CLOB");

                    b.Property<string>("Diesel_Type")
                        .HasColumnType("CLOB");

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .HasColumnType("CLOB");

                    b.Property<int>("Power")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.ToTable("DieselLocomotiveInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Diesel_train_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("BaseInfo")
                        .HasColumnType("CLOB");

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("Power")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.ToTable("Diesel_Train_Infos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Diesel_trainz", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Depo")
                        .HasColumnType("CLOB");

                    b.Property<string>("ImgSrc")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Number")
                        .HasColumnType("CLOB");

                    b.Property<int>("VagonCount")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.ToTable("Diesel_Trinzs");
                });

            modelBuilder.Entity("TrainzInfo.Models.Electic_locomotive", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ALlPowerP")
                        .HasColumnType("CLOB");

                    b.Property<string>("Depot")
                        .HasColumnType("CLOB");

                    b.Property<string>("DieselPower")
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("SectionCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Seria")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("Speed")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("User")
                        .HasColumnType("CLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.ToTable("Electic_Locomotives");
                });

            modelBuilder.Entity("TrainzInfo.Models.ElectricTrain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DepotCity")
                        .HasColumnType("CLOB");

                    b.Property<string>("DepotTrain")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<string>("IsProof")
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("LastKvr")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("PlaceKvr")
                        .HasColumnType("CLOB");

                    b.Property<string>("Plant")
                        .HasColumnType("CLOB");

                    b.Property<string>("User")
                        .HasColumnType("CLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("VagonsCountP")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Electrics");
                });

            modelBuilder.Entity("TrainzInfo.Models.ElectrickTrainsList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Depo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("NumberTrain")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("ElectrickTrainsList");
                });

            modelBuilder.Entity("TrainzInfo.Models.ElectrickTrainzInformation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllInformation")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Imgsrc")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("ElectrickTrainzInformation");
                });

            modelBuilder.Entity("TrainzInfo.Models.Electrick_Lockomotive_Info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllInfo")
                        .HasColumnType("CLOB");

                    b.Property<string>("Baseinfo")
                        .HasColumnType("CLOB");

                    b.Property<string>("Diesel")
                        .HasColumnType("CLOB");

                    b.Property<string>("Electric_Type")
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .HasColumnType("CLOB");

                    b.Property<string>("Power")
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Electrick_Lockomotive_Infos");
                });

            modelBuilder.Entity("TrainzInfo.Models.IpAdresses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("IpAddres")
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("IpAdresses");
                });

            modelBuilder.Entity("TrainzInfo.Models.ListRollingStone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Depot")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("ListRollingStones");
                });

            modelBuilder.Entity("TrainzInfo.Models.LocomotiveBaseInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("locomotiveBaseInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Locomotive_series", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Seria")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Locomotive_Series");
                });

            modelBuilder.Entity("TrainzInfo.Models.LocomotivesType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("LocomotivesTypes");
                });

            modelBuilder.Entity("TrainzInfo.Models.MainImages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageType")
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("MainImages");
                });

            modelBuilder.Entity("TrainzInfo.Models.Metro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Metros");
                });

            modelBuilder.Entity("TrainzInfo.Models.MetroLines", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountStation")
                        .HasColumnType("NUMBER(10)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<string>("Metro")
                        .HasColumnType("CLOB");

                    b.Property<string>("NameLine")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("MetroLines");
                });

            modelBuilder.Entity("TrainzInfo.Models.MetroStation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<int>("MetroID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MetroLine")
                        .HasColumnType("CLOB");

                    b.Property<int>("MetroLineId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("MetroStations");
                });

            modelBuilder.Entity("TrainzInfo.Models.NewsComments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasMaxLength(10);

                    b.Property<int>("NewsID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("NewsComments");
                });

            modelBuilder.Entity("TrainzInfo.Models.NewsInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseNewsInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<string>("Imgsrc")
                        .HasColumnType("CLOB");

                    b.Property<string>("NameNews")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("NewsImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("NewsInfoAll")
                        .HasColumnType("CLOB");

                    b.Property<string>("user")
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("NewsInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Oblast", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("OblCenter")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Oblasts");
                });

            modelBuilder.Entity("TrainzInfo.Models.PassangerCarriegesInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("PassangerCarriegesInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.PassangerCarriere", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calss")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("CountPlace")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ImgsrcInside")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("ImgsrcOutside")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("PassangerCarrieres");
                });

            modelBuilder.Entity("TrainzInfo.Models.Plants", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("plants");
                });

            modelBuilder.Entity("TrainzInfo.Models.RailwayUsersPhoto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityFrom")
                        .HasColumnType("CLOB");

                    b.Property<string>("CitytTo")
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageType")
                        .HasColumnType("CLOB");

                    b.Property<string>("Information")
                        .HasColumnType("CLOB");

                    b.Property<string>("IsProof")
                        .HasColumnType("CLOB");

                    b.Property<string>("NameUser")
                        .HasColumnType("CLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.ToTable("RailwayUsersPhotos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Rules")
                        .HasColumnType("CLOB");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TrainzInfo.Models.StationInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("stationInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Stations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("DopImgSrc")
                        .HasColumnType("CLOB");

                    b.Property<string>("DopImgSrcSec")
                        .HasColumnType("CLOB");

                    b.Property<string>("DopImgSrcThd")
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<string>("Imgsrc")
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Oblast")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Railway")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainzInfo.Models.StationsShadule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImgTrain")
                        .HasColumnType("CLOB");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("TimeOfArrive")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("TimeOfDepet")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("TrainInfo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("UzFilia")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("StationsShadules");
                });

            modelBuilder.Entity("TrainzInfo.Models.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status_namr")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TrainzInfo.Models.SuburbanTrainsInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("SuburbanTrainsInfos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Train", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameOfTrain")
                        .HasColumnType("CLOB");

                    b.Property<int>("Number")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StationFrom")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("StationTo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("TrainzInfo.Models.TrainzStations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameStationStop")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("NumberOFTrain")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("TimeOfArrive")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("TimeOfDepet")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("id");

                    b.ToTable("TrainzStations");
                });

            modelBuilder.Entity("TrainzInfo.Models.TrainzType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasColumnType("CLOB");

                    b.HasKey("Id");

                    b.ToTable("TrainzTypes");
                });

            modelBuilder.Entity("TrainzInfo.Models.TypeOfPassTrain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("TypeOfPassTrains");
                });

            modelBuilder.Entity("TrainzInfo.Models.UkrainsRailways", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("UkrainsRailways");
                });

            modelBuilder.Entity("TrainzInfo.Models.UserLocomotivePhotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<string>("NameLocomotive")
                        .HasColumnType("CLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("Id");

                    b.ToTable("UserLocomotivePhotos");
                });

            modelBuilder.Entity("TrainzInfo.Models.UserTrainzPhoto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseInfo")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageType")
                        .HasColumnType("CLOB");

                    b.Property<string>("LocmotiveName")
                        .HasColumnType("CLOB");

                    b.Property<string>("Marshrute")
                        .HasColumnType("CLOB");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("id");

                    b.ToTable("UserTrainzPhotos");
                });

            modelBuilder.Entity("TrainzInfo.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageMimeTypeOfData")
                        .HasColumnType("CLOB");

                    b.Property<string>("IpAddress")
                        .HasColumnType("CLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Role")
                        .HasColumnType("CLOB");

                    b.Property<string>("Status")
                        .HasColumnType("CLOB");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
